// This file is auto-generated by ./bin/rails stimulus:manifest:update
// Run that command whenever you add a new controller or create them with
// ./bin/rails generate stimulus controllerName

import { application } from "./application"

import NumeralController from "./numeral_controller"
application.register("numeral", NumeralController)

import PhoneNumberController from "./phone_number_controller"
application.register("phone-number", PhoneNumberController)

import TaskModalController from "./task_modal_controller"
application.register("task-modal", TaskModalController)

import TaskStateController from "./task_state_controller"
application.register("task-state", TaskStateController)

import UserPopoverController from "./user_popover_controller"
application.register("user-popover", UserPopoverController)
