// This file is auto-generated by ./bin/rails stimulus:manifest:update
// Run that command whenever you add a new controller or create them with
// ./bin/rails generate stimulus controllerName

import { application } from "./application"

import NumeralController from "./numeral_controller"
application.register("numeral", NumeralController)

import TaskStateController from "./task_state_controller"
application.register("task-state", TaskStateController)
